name: Fetch Exchange Rates

on:
  push:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  fetch_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch exchange rates
        env:
          EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/$EXCHANGE_API_KEY/latest/USD" -o rates.json

      - name: Commit and push updated rates.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rates.json
          git commit -m "Update exchange rates [skip ci]" || echo "No changes to commit"
          git push
