name: Fetch Exchange Rates

on:
  push:
    branches:
      - main

jobs:
  fetch_rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Show secret API key (masked by GitHub)
        env:
          EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
        run: |
          echo "Using secret API key: $EXCHANGE_API_KEY"
